# Generated by Django 5.2.6 on 2026-04-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippingcomp', '0003_booking_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='cruiseproduct',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
