# Generated by Django 5.2.6 on 2026-06-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippingcomp', '0004_remove_bookingproduct_price_cruiseproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='min_groupsize',
            field=models.SmallIntegerField(default=0, verbose_name='Minimal group size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='max_groupsize',
            field=models.SmallIntegerField(verbose_name='Maximum group size'),
        ),
    ]
