# Generated by Django 5.2.6 on 2026-06-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippingcomp', '0005_cruise_min_groupsize_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cruise',
            options={'ordering': ['from_date', 'to_date']},
        ),
        migrations.AddField(
            model_name='booking',
            name='pax',
            field=models.SmallIntegerField(default=1),
        ),
    ]
