# Generated by Django 5.2.6 on 2026-06-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippingcomp', '0006_alter_cruise_options_booking_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Option'), (1, 'Confirmed'), (2, 'On hold'), (-1, 'Cancelled')], default=0, verbose_name='Status'),
        ),
    ]
