# Generated by Django 5.2.6 on 2026-06-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippingcomp', '0008_alter_booking_options_alter_booking_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shippingcomp.booking'),
        ),
    ]
