# Generated by Django 5.2.6 on 2026-09-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippingcomp', '0009_coupon_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Draft'), (0, 'Open'), (20, 'Closed'), (50, 'Cancelled')], default=-1, verbose_name='Status'),
        ),
    ]
